// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_RUNNING   Status = 0
	Status_STOPPED   Status = 1
	Status_UNHEALTHY Status = 2
)

var Status_name = map[int32]string{
	0: "RUNNING",
	1: "STOPPED",
	2: "UNHEALTHY",
}

var Status_value = map[string]int32{
	"RUNNING":   0,
	"STOPPED":   1,
	"UNHEALTHY": 2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{0}
}

type ClusterData struct {
	LoadBalancer         []*LoadBalancer `protobuf:"bytes,1,rep,name=loadBalancer,proto3" json:"loadBalancer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ClusterData) Reset()         { *m = ClusterData{} }
func (m *ClusterData) String() string { return proto.CompactTextString(m) }
func (*ClusterData) ProtoMessage()    {}
func (*ClusterData) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{0}
}

func (m *ClusterData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterData.Unmarshal(m, b)
}
func (m *ClusterData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterData.Marshal(b, m, deterministic)
}
func (m *ClusterData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterData.Merge(m, src)
}
func (m *ClusterData) XXX_Size() int {
	return xxx_messageInfo_ClusterData.Size(m)
}
func (m *ClusterData) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterData.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterData proto.InternalMessageInfo

func (m *ClusterData) GetLoadBalancer() []*LoadBalancer {
	if m != nil {
		return m.LoadBalancer
	}
	return nil
}

type LoadBalancer struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TargetGroup          []*TargetGroup `protobuf:"bytes,2,rep,name=targetGroup,proto3" json:"targetGroup,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *LoadBalancer) Reset()         { *m = LoadBalancer{} }
func (m *LoadBalancer) String() string { return proto.CompactTextString(m) }
func (*LoadBalancer) ProtoMessage()    {}
func (*LoadBalancer) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{1}
}

func (m *LoadBalancer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadBalancer.Unmarshal(m, b)
}
func (m *LoadBalancer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadBalancer.Marshal(b, m, deterministic)
}
func (m *LoadBalancer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadBalancer.Merge(m, src)
}
func (m *LoadBalancer) XXX_Size() int {
	return xxx_messageInfo_LoadBalancer.Size(m)
}
func (m *LoadBalancer) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadBalancer.DiscardUnknown(m)
}

var xxx_messageInfo_LoadBalancer proto.InternalMessageInfo

func (m *LoadBalancer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoadBalancer) GetTargetGroup() []*TargetGroup {
	if m != nil {
		return m.TargetGroup
	}
	return nil
}

type TargetGroup struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Instance             []*Instance `protobuf:"bytes,2,rep,name=instance,proto3" json:"instance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TargetGroup) Reset()         { *m = TargetGroup{} }
func (m *TargetGroup) String() string { return proto.CompactTextString(m) }
func (*TargetGroup) ProtoMessage()    {}
func (*TargetGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{2}
}

func (m *TargetGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetGroup.Unmarshal(m, b)
}
func (m *TargetGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetGroup.Marshal(b, m, deterministic)
}
func (m *TargetGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetGroup.Merge(m, src)
}
func (m *TargetGroup) XXX_Size() int {
	return xxx_messageInfo_TargetGroup.Size(m)
}
func (m *TargetGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetGroup.DiscardUnknown(m)
}

var xxx_messageInfo_TargetGroup proto.InternalMessageInfo

func (m *TargetGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TargetGroup) GetInstance() []*Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

type Instance struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status               Status   `protobuf:"varint,2,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{3}
}

func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (m *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(m, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Instance) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_RUNNING
}

func init() {
	proto.RegisterEnum("proto.Status", Status_name, Status_value)
	proto.RegisterType((*ClusterData)(nil), "proto.ClusterData")
	proto.RegisterType((*LoadBalancer)(nil), "proto.LoadBalancer")
	proto.RegisterType((*TargetGroup)(nil), "proto.TargetGroup")
	proto.RegisterType((*Instance)(nil), "proto.Instance")
}

func init() { proto.RegisterFile("proto/message.proto", fileDescriptor_33f3a5e1293a7bcd) }

var fileDescriptor_33f3a5e1293a7bcd = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8d, 0xc1, 0x4b, 0xc3, 0x30,
	0x18, 0xc5, 0x4d, 0xd5, 0xba, 0x7d, 0xd9, 0xb4, 0x64, 0x97, 0x1e, 0x4b, 0x41, 0x28, 0x0a, 0x13,
	0xa7, 0xe0, 0x59, 0x5d, 0xdd, 0x06, 0x23, 0x8e, 0xac, 0x03, 0x3d, 0x7e, 0x6a, 0x18, 0x42, 0xd7,
	0x8e, 0x24, 0xfd, 0xff, 0x65, 0x59, 0xd4, 0x0c, 0x7a, 0x4a, 0xde, 0xfb, 0xbd, 0xfc, 0x02, 0x83,
	0xad, 0xaa, 0x4d, 0x7d, 0xb3, 0x91, 0x5a, 0xe3, 0x5a, 0x0e, 0x6d, 0x62, 0xa7, 0xf6, 0x48, 0x5f,
	0x80, 0x3e, 0x97, 0x8d, 0x36, 0x52, 0x8d, 0xd1, 0x20, 0x7b, 0x80, 0x5e, 0x59, 0xe3, 0xd7, 0x13,
	0x96, 0x58, 0x7d, 0x4a, 0x15, 0x93, 0xe4, 0x38, 0xa3, 0xa3, 0xc1, 0xfe, 0xcd, 0x70, 0xee, 0x21,
	0x71, 0x30, 0x4c, 0xdf, 0xa0, 0xe7, 0x53, 0xc6, 0xe0, 0xa4, 0xc2, 0x8d, 0x8c, 0x49, 0x42, 0xb2,
	0xae, 0xb0, 0x77, 0x76, 0x0f, 0xd4, 0xa0, 0x5a, 0x4b, 0x33, 0x51, 0x75, 0xb3, 0x8d, 0x03, 0xeb,
	0x66, 0xce, 0x5d, 0xfc, 0x13, 0xe1, 0xcf, 0x52, 0x0e, 0xd4, 0x63, 0xad, 0xe2, 0x6b, 0xe8, 0x7c,
	0x57, 0xda, 0xec, 0x7e, 0x76, 0xd6, 0x0b, 0x67, 0x9d, 0xb9, 0x5a, 0xfc, 0x0d, 0xd2, 0x1c, 0x3a,
	0xbf, 0x6d, 0xab, 0xec, 0x12, 0x42, 0x6d, 0xd0, 0x34, 0x3a, 0x0e, 0x12, 0x92, 0x9d, 0x8f, 0xfa,
	0x4e, 0xb5, 0xb4, 0xa5, 0x70, 0xf0, 0xea, 0x16, 0xc2, 0x7d, 0xc3, 0x28, 0x9c, 0x89, 0x15, 0xe7,
	0x33, 0x3e, 0x89, 0x8e, 0x76, 0x61, 0x59, 0xbc, 0x2e, 0x16, 0xf9, 0x38, 0x22, 0xac, 0x0f, 0xdd,
	0x15, 0x9f, 0xe6, 0x8f, 0xf3, 0x62, 0xfa, 0x1e, 0x05, 0x1f, 0xa1, 0x15, 0xdd, 0xfd, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x3a, 0x00, 0xab, 0x21, 0x90, 0x01, 0x00, 0x00,
}
